swagger: "2.0"
info:
  title: Fastify API
  description: API documentation
  version: "1.0.0"
host: localhost:3000
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /users:
    get:
      description: Get all users
      responses:
        200:
          description: Successful response
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
                email:
                  type: string
          examples:
            application/json:
              [
                {
                  "id": 1,
                  "name": "Jane Doe",
                  "email": "jane.doe@example.com",
                },
                {
                  "id": 2,
                  "name": "John Doe",
                  "email": "john.doe@example.com",
                },
              ]
